[project]
name = "dvplc"
description = "CLI app to convert Dava SmartDLC .dvpl files used in Wargaming.net's World of Tanks Bliz MMO game"
readme = "README.md"
version = "0.1.2"
license = {text = "MIT License"}
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "lz4",
	"aiofiles",
	"aioconsole",
	"importlib-metadata"
]
authors = [ { name="Jylpah", email="Jylpah@gmail.com"} ]


[project.scripts]
dvplc = "dvplc.dvplc:__main__"

[project.urls]
"Homepage" = "https://github.com/Jylpah/dvplc"

[tool.setuptools.packages.find]
# All the following settings are optional:
exclude = ["dvplc.tests*"]  # empty by default

[mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/dvplc/"
