# static typing stub for FileQueue

import asyncio
from typing import Optional

class FileQueue(asyncio.Queue):
	def __init__(self, base: Optional[str] = None, maxsize: int = 0, filter: str = '*', 
				exclude: bool = False, case_sensitive: bool = False): ...

	def set_filter(self, filter: str = None, exclude: bool = None, case_sensitive: bool = None ): ...

	async def mk_queue(self, files: list[str]) -> bool: ...

	async def put(self, filename: str) -> None: ...

	def count(self) -> int: ...

	def _match(self, filename: str) -> bool: ...